#ifndef BUCKET_H
#define BUCKET_H

#include "../utils/utils.h"
#include "env/env.h"
#include "globals/globals.h"

namespace bucket
{
    /**
     * @brief The endpoint URL for the sensor API.
     */
    String api_server = ENV_API_SERVER;
    String debugDataEndpoint = "/api/debug/sensor";
    
    String createSensorEndpoint; // Endpoint for creating a new bucket sensor.
    String registerBucketData; // Endpoint for data generated by the bucket sensor.

    /**
     * @brief Sends a POST request to the sensor endpoint with the provided JSON serialized data.
     *
     * @param data A JSON serialized string containing the data to be sent in the POST request.
     * @return The response from the sensor endpoint as a string.
     */
    JsonDocument post(String data)
    {
        registerBucketData = api_server + (isDebugMode ? debugDataEndpoint : "/api/sensor/bucketData");
        return utils::postData(registerBucketData, data);
    }

    JsonDocument create(String data)
    {
        createSensorEndpoint = api_server + (isDebugMode ? debugDataEndpoint : "/api/sensor/bucket");
        return utils::postData(createSensorEndpoint, data);
    }

} // namespace sensor

#endif // BUCKET_H