#ifndef BUCKET_H
#define BUCKET_H

#include "../utils/utils.h"

namespace bucket
{
    /**
     * @brief The endpoint URL for the sensor API.
     */
    // String createSensorEndpoint = "http://blindspot.media.mit.edu:8000/api/sensor/bucket"; // Endpoint for creating a new bucket sensor.
    // String registerBucketData = "http://blindspot.media.mit.edu:8000/api/sensor/bucketData"; // Endpoint for data generated by the bucket sensor.
    String createSensorEndpoint = "http://192.168.1.59:8000/api/sensor/bucket"; // Endpoint for creating a new bucket sensor.
    String registerBucketData = "http://192.168.1.59:8000/api/sensor/bucketData"; // Endpoint for data generated by the bucket sensor.

    /**
     * @brief Sends a POST request to the sensor endpoint with the provided JSON serialized data.
     *
     * @param data A JSON serialized string containing the data to be sent in the POST request.
     * @return The response from the sensor endpoint as a string.
     */
    JsonDocument post(String data)
    {
        return utils::postData(registerBucketData, data);
    }

    JsonDocument create(String data)
    {
        return utils::postData(createSensorEndpoint, data);
    }

} // namespace sensor

#endif // BUCKET_H